# Generated by Django 5.2.12 on 2026-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="status",
            field=models.CharField(
                choices=[("ATIVO", "Ativo"), ("INATIVO", "Inativo")],
                default="ATIVO",
                max_length=7,
            ),
        ),
    ]
